site_name: Basic API Toolkit

#extra_css:
#  - css/ibx.css

nav:
  - IBX-Tools: index.md
  - User Guides:
      - Classes:
          - wapi: user-guide/classes/wapi.md
          - fileop: user-guide/classes/fileop.md
          - service: user-guide/classes/service.md
      - Examples:
          - CSV Export: user-guide/examples/csvexport.md
          - CSV Import: user-guide/examples/csvimport.md
          - Get Configuration: user-guide/examples/get_config.md
          - Get Log: user-guide/examples/get_log.md
          - Get Support Bundle: user-guide/examples/get_supportbundle.md
          - Grid Backup: user-guide/examples/grid_backup.md
          - Grid Restore: user-guide/examples/grid_restore.md
          - Restart Service: user-guide/examples/restart_service.md
          - Restart Status: user-guide/examples/restart_status.md
  - Change Log: changelog.md
  - License: LICENSE.md

theme:
  font:
    text: Lato

  palette:
    primary: black
    accent: green

  logo: assets/logo.svg
  name: material

  markdown_extensions:
    - pymdownx.highlight:
        pygments_lang_class: true
#    - pymdownx.superfences
#    - pymdownx.inlinehilite
#    - pymdownx.snippets
#    - pymdownx.superfences
#    - pymdownx.arithmatex:
#        generic: true

features:
  - navigation.tabs
  - navigation.sections
  - navigation.path
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

plugins:
  - search
  - mkdocstrings

copyright: |
  &copy; 2023 <a href="https://infoblox.com" target= "_blank" rel="noopener">Infoblox</a>
