site_name: Basic API Toolkit
site_author: Michael Smith, Patrick Piper

# Repository
repo_name: Infoblox-PS/ibx-tools
repo_url: https://github.com/Infoblox-PS/ibx-tools

# Copyright
copyright: |
  &copy; 2023 <a href="https://infoblox.com" target= "_blank" rel="noopener">Infoblox</a>

# Configuration
theme:
  #  extra_css:
  #    - stylesheets/extra.css
  name: material
  sticky_navigation: true
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Lato
    code: Lato Mono
  logo: assets/Infoblox_Logo_Primary_Reverse_RGB.png
  favicon: assets/infoblox-favicon-green.svg

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings
#  - git-authors
#  - git-committers:
#      repository: Infoblox-PS/ibx-tools
#      branch: main

nav:
  - Home: index.md
  - User Guides:
      - Classes:
          - wapi: classes/wapi.md
          - fileop: classes/fileop.md
          - service: classes/service.md
          - ibx_logger: classes/logger.md

      - Examples:
          - CSV Export: examples/csvexport.md
          - CSV Import: examples/csvimport.md
          - Get File: examples/get_file.md
          - Get Log: examples/get_log.md
          - Get Support Bundle: examples/get_supportbundle.md
          - Grid Backup: examples/grid_backup.md
          - Grid Restore: examples/grid_restore.md
          - Restart Service: examples/restart_service.md
          - Restart Status: examples/restart_status.md
  - Change Log: changelog.md
  - License: LICENSE.md

extra:
  generator: false
